### ISSUE TITLE
Issue w/ json file

### ISSUE THREAD

**Issue by ThaumielSparrow** [snarticuno/muledump-2#1]
Followed all instructions exactly,

when I type muledump-2-master.exe "config.json" my cmd says: 
error decoding config file: invalid character ']' looking for beginning of value
any ideas?

**Comment by GhostMaree** [comment]
try
`muledump-2-master.exe config.json`

**Comment by ThaumielSparrow** [comment]
Still doesn't work. Any other ideas?

**Comment by ThaumielSparrow** [comment]
gg no re its fixed for some reason
